//! Generated-stub alias (`---@alias`) declarations.

use super::Alias;

pub(super) const ALIASES: &[Alias] = &[
    Alias {
        name: "kage.LogLevel",
        doc: &["Levels accepted by `kage.log`."],
        variants: &["trace", "debug", "info", "warn", "error"],
    },
    Alias {
        name: "kage.NotifyLevel",
        doc: &["Levels accepted by `kage.ui.notify` / `kage.notify`."],
        variants: &["info", "warning", "error"],
    },
    Alias {
        name: "kage.ToolRisk",
        doc: &["Permission tier for a registered tool."],
        variants: &["read", "write", "exec", "network"],
    },
    Alias {
        name: "kage.ArgKind",
        doc: &["A declared command argument kind."],
        variants: &["text", "choice", "path", "session", "flag"],
    },
    Alias {
        name: "kage.Capability",
        doc: &[
            "An elevated capability a plugin may request. Granted",
            "per-plugin in `[plugins.capabilities]`.",
        ],
        variants: &["session_write", "exec", "env", "net"],
    },
    Alias {
        name: "kage.OptionSource",
        doc: &["Where the current value of an option came from."],
        variants: &["default", "toml", "lua", "runtime"],
    },
    Alias {
        name: "kage.KeymapMode",
        doc: &[
            "A keymap mode: `n` vim normal (both panes), `b` vim normal",
            "with the conversation pane focused, `i` insert and the",
            "modeless editor, `v` visual, `g` any editing state.",
        ],
        variants: &["n", "b", "i", "v", "g"],
    },
    Alias {
        name: "kage.SlotName",
        doc: &["A chrome region `kage.ui.set_slot` fills."],
        variants: &["header", "activity", "input_pill", "footer", "start"],
    },
    Alias {
        name: "kage.Component",
        doc: &[
            "A built-in slot component, painted by the host every frame.",
            "`sessions` and `notices` paint only in `start`. `breadcrumb`",
            "paints the agent on screen and nothing in the main view, where",
            "`title` paints instead.",
        ],
        variants: &[
            "brand",
            "breadcrumb",
            "title",
            "model",
            "widgets",
            "search",
            "session",
            "working",
            "activity",
            "context",
            "tokens",
            "thinking",
            "permission",
            "mode",
            "hint",
            "cwd",
            "version",
            "sessions",
            "notices",
        ],
    },
    Alias {
        name: "kage.Event",
        doc: &[
            "Every event name `kage.on` and `kage.api.autocmd_create`",
            "accept. Notification events ignore the handler return;",
            "transform events chain it; predicate and session-op events",
            "interpret it. `user` fires only through",
            "`kage.api.autocmd_exec`.",
        ],
        variants: &[
            "before_agent_start",
            "agent_start",
            "agent_end",
            "turn_start",
            "turn_end",
            "message_start",
            "message_update",
            "message_end",
            "after_provider_response",
            "tool_call",
            "tool_update",
            "tool_result",
            "model_select",
            "thinking_level_select",
            "user_bash",
            "permission_mode_select",
            "option_set",
            "color_scheme",
            "user",
            "transform_context",
            "before_provider_request",
            "compact_prepare",
            "should_stop_after_turn",
            "session_before_switch",
            "session_before_fork",
            "resources_discover",
        ],
    },
];
