//! The `lua-language-server` definition stub for the `kage` global,
//! rendered from [`super::surface`], so the stub cannot drift from the
//! Rust bindings. `cargo xtask gen-lua-types` writes it to
//! `plugins/types/kage.lua`, and `kage init` writes it next to a
//! generated `.luarc.json`.

use std::fmt::Write as _;

use crate::spec;

const HEADER: &str = "\
---@meta
---
--- Type definitions for the `kage` plugin API.
---
--- GENERATED by `cargo xtask gen-lua-types` from the kage-plugin spec
--- (`crates/kage-plugin/src/spec.rs`). Do not edit by hand: edit that
--- spec and regenerate. CI fails if this file drifts from it.
---
--- This file is a `lua-language-server` definition stub: it declares
--- the shape of the `kage` global so editors give hover docs,
--- completion, and argument checking inside `*.lua` plugins. It ships
--- with the kage repo and is copied to
--- `~/.local/share/kage/types/kage.lua` by `kage init`, which also
--- writes a `.luarc.json` pointing the language server at it.
---
--- Nothing here runs: `---@meta` marks the whole file definitions-only.
--- The single source of truth for behavior is the Rust implementation
--- in `crates/kage-plugin`.";

fn doc_lines(out: &mut String, doc: &[&str]) {
    for line in doc {
        if line.is_empty() {
            out.push_str("---\n");
        } else {
            let _ = writeln!(out, "--- {line}");
        }
    }
}

/// Strip a trailing `?` (optional marker) from a field name.
fn bare(name: &str) -> &str {
    name.strip_suffix('?').unwrap_or(name)
}

/// Render the whole stub deterministically from the spec.
#[must_use]
pub fn lua_stub() -> String {
    let surface = spec::surface();
    let mut s = String::new();
    s.push_str(HEADER);
    s.push('\n');

    for a in surface.aliases {
        s.push('\n');
        doc_lines(&mut s, a.doc);
        if a.variants.len() <= 5 {
            let joined = a
                .variants
                .iter()
                .map(|v| format!("\"{v}\""))
                .collect::<Vec<_>>()
                .join("|");
            let _ = writeln!(s, "---@alias {} {joined}", a.name);
        } else {
            let _ = writeln!(s, "---@alias {}", a.name);
            for v in a.variants {
                let _ = writeln!(s, "---| \"{v}\"");
            }
        }
    }

    for c in surface.classes {
        s.push('\n');
        doc_lines(&mut s, c.doc);
        let _ = writeln!(s, "---@class {}", c.name);
        for f in c.fields {
            let opt = if f.name.ends_with('?') { "?" } else { "" };
            let tail = if f.doc.is_empty() {
                String::new()
            } else {
                format!(" {}", f.doc)
            };
            let _ = writeln!(s, "---@field {}{opt} {}{tail}", bare(f.name), f.ty);
        }
    }

    s.push('\n');
    render_options(&mut s, surface.options);
    s.push('\n');
    render_actions(&mut s, surface.actions);

    // Declare `kage` as a GLOBAL, not a `local` module. The host
    // injects `kage` as a global into every plugin; modelling it as a
    // local module (with a trailing `return kage`) makes
    // lua-language-server treat references in plugin files as
    // undefined globals. A global `---@class kage` table with no
    // return types the injected global correctly and keeps
    // `lua-language-server --check` clean on real plugins.
    s.push_str("\n---@class kage\nkage = {}\n");
    s.push_str(
        "\n--- Options by name. Assigning validates the value, records the\n\
         --- source and fires `option_set`.\n\
         ---@type kage.Options\n\
         kage.opt = {}\n",
    );
    s.push_str(
        "\n--- Rust actions to use as a mapping rhs.\n\
         ---@type kage.Actions\n\
         kage.action = {}\n",
    );

    // Base functions, then capability-gated ones. Gated functions are
    // rendered the same way (so editors still offer them when the
    // plugin has the capability); their doc already states the
    // requirement. They share the `declared` set so a sub-table is
    // still declared exactly once.
    let mut declared: Vec<&'static str> = Vec::new();
    for f in surface.funcs {
        emit_func(&mut s, &mut declared, surface.tables, f);
    }
    for g in surface.gated {
        emit_func(&mut s, &mut declared, surface.tables, &g.func);
    }

    // No trailing `return kage`: this is a global definition file, not
    // a module. (`---@meta` already marks it definitions-only.)
    s
}

/// Render the `kage.Options` class from the option registry.
fn render_options(s: &mut String, options: &[spec::OptionDef]) {
    s.push_str("--- Every option `kage.opt` reads and writes.\n---@class kage.Options\n");
    for def in options {
        let ty = match def.kind {
            spec::OptionKind::Bool { .. } => "boolean".to_owned(),
            spec::OptionKind::Int { .. } => "integer".to_owned(),
            spec::OptionKind::Fraction { .. } => "number".to_owned(),
            spec::OptionKind::Choice { values, .. } => values
                .iter()
                .map(|v| format!("\"{v}\""))
                .collect::<Vec<_>>()
                .join("|"),
            spec::OptionKind::Str { .. } | spec::OptionKind::Key { .. } => "string".to_owned(),
        };
        let _ = writeln!(s, "---@field {} {ty} {}", def.name, def.doc);
    }
}

/// Render the `kage.Actions` class from the action list. An action
/// that takes an argument is a function under its lowercase name.
fn render_actions(s: &mut String, actions: &[spec::ActionDef]) {
    s.push_str("--- Every action `kage.action` holds.\n---@class kage.Actions\n");
    for def in actions {
        if def.arg {
            let _ = writeln!(
                s,
                "---@field {} fun(n: integer): kage.Action {}",
                def.name.to_ascii_lowercase(),
                def.doc
            );
        } else {
            let _ = writeln!(s, "---@field {} kage.Action {}", def.name, def.doc);
        }
    }
}

/// Emit one function: its sub-table declaration (once), doc, the API
/// generation that introduced it, params, return, and stub body.
fn emit_func(
    s: &mut String,
    declared: &mut Vec<&'static str>,
    tables: &'static [spec::Table],
    f: &'static spec::Func,
) {
    // Declare any sub-table the function lives on, once, in spec
    // order, just before its first function.
    if let Some((table, _)) = f.path.rsplit_once('.')
        && table != "kage"
        && !declared.contains(&table)
    {
        if let Some(t) = tables.iter().find(|t| t.path == table) {
            s.push('\n');
            let _ = writeln!(s, "--- {}", t.class_doc);
            let _ = writeln!(s, "---@class {table}");
            let _ = writeln!(s, "{table} = {{}}");
        }
        declared.push(table);
    }
    s.push('\n');
    doc_lines(s, f.doc);
    let _ = writeln!(s, "--- Since API {}.", f.since);
    let mut args: Vec<String> = Vec::new();
    for p in f.params {
        let opt = if p.name.ends_with('?') { "?" } else { "" };
        let tail = if p.doc.is_empty() {
            String::new()
        } else {
            format!(" {}", p.doc)
        };
        let _ = writeln!(s, "---@param {}{opt} {}{tail}", bare(p.name), p.ty);
        args.push(bare(p.name).to_owned());
    }
    if let Some(ret) = f.ret {
        let _ = writeln!(s, "---@return {ret}");
    }
    let _ = writeln!(s, "function {}({}) end", f.path, args.join(", "));
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn render_is_deterministic() {
        assert_eq!(lua_stub(), lua_stub());
    }

    #[test]
    fn render_declares_kage_as_a_global() {
        let s = lua_stub();
        assert!(s.starts_with("---@meta\n"));
        assert!(s.contains("---@class kage\nkage = {}\n"));
        // It is a global definition file: no `local` shadow, no
        // module `return` statement (which would make plugin-file
        // references read as undefined globals to
        // lua-language-server). Checked as a statement, not a
        // substring, so `---@return kage.Usage` does not trip it.
        assert!(!s.contains("local kage = {}"));
        assert!(!s.contains("\nreturn kage"));
        assert!(!s.trim_end().ends_with("return kage"));
    }

    #[test]
    fn every_func_path_is_emitted() {
        let s = lua_stub();
        let surface = spec::surface();
        let paths = surface
            .funcs
            .iter()
            .map(|f| f.path)
            .chain(surface.gated.iter().map(|g| g.func.path));
        for path in paths {
            assert!(s.contains(&format!("function {path}(")), "missing {path}");
        }
    }

    #[test]
    fn every_func_states_its_api_generation() {
        let s = lua_stub();
        assert!(s.contains("--- Since API 1.\n---@return integer\nfunction kage.now_ms() end"));
        assert!(s.contains("--- Since API 2.\n---@param event kage.Event"));
    }

    #[test]
    fn sub_tables_are_declared_once_before_use() {
        let s = lua_stub();
        for t in spec::surface().tables {
            let decl = format!("{} = {{}}", t.path);
            assert_eq!(
                s.matches(&decl).count(),
                1,
                "{} should be declared exactly once",
                t.path
            );
        }
    }

    #[test]
    fn options_class_is_generated_from_the_registry() {
        let s = lua_stub();
        assert!(s.contains("---@class kage.Options\n---@field theme string "));
        assert!(s.contains("---@field editor \"vim\"|\"modeless\" "));
        assert!(s.contains("---@field mouse boolean "));
        assert!(s.contains("---@type kage.Options\nkage.opt = {}\n"));
    }

    #[test]
    fn actions_class_is_generated_from_the_action_list() {
        let s = lua_stub();
        assert!(s.contains("---@class kage.Actions\n---@field Cancel kage.Action "));
        assert!(s.contains("---@field scroll fun(n: integer): kage.Action "));
        assert!(s.contains("---@type kage.Actions\nkage.action = {}\n"));
    }

    #[test]
    fn long_unions_use_multiline_form() {
        let s = lua_stub();
        // kage.Event has > 5 variants -> multi-line `---| "x"`.
        assert!(s.contains("---@alias kage.Event\n---| \"before_agent_start\""));
        // Short alias stays inline.
        assert!(s.contains(r#"---@alias kage.LogLevel "trace"|"debug""#));
    }
}
