[package]
name = "xtask"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[[bin]]
name = "xtask"
path = "src/main.rs"

[dependencies]
clap.workspace = true
ureq.workspace = true
kage-core.workspace = true
kage-plugin.workspace = true
kage-provider.workspace = true
