---@meta
---
--- Type definitions for the `kage` plugin API.
---
--- GENERATED by `cargo xtask gen-lua-types` from the kage-plugin spec
--- (`crates/kage-plugin/src/spec.rs`). Do not edit by hand: edit that
--- spec and regenerate. CI fails if this file drifts from it.
---
--- This file is a `lua-language-server` definition stub: it declares
--- the shape of the `kage` global so editors give hover docs,
--- completion, and argument checking inside `*.lua` plugins. It ships
--- with the kage repo and is copied to
--- `~/.local/share/kage/types/kage.lua` by `kage init`, which also
--- writes a `.luarc.json` pointing the language server at it.
---
--- Nothing here runs: `---@meta` marks the whole file definitions-only.
--- The single source of truth for behavior is the Rust implementation
--- in `crates/kage-plugin`.

--- Levels accepted by `kage.log`.
---@alias kage.LogLevel "trace"|"debug"|"info"|"warn"|"error"

--- Levels accepted by `kage.ui.notify` / `kage.notify`.
---@alias kage.NotifyLevel "info"|"warning"|"error"

--- Permission tier for a registered tool.
---@alias kage.ToolRisk "read"|"write"|"network"

--- A declared command argument kind.
---@alias kage.ArgKind "text"|"choice"|"path"|"session"|"flag"

--- Every event name `kage.on` accepts. Notification events
--- ignore the handler return; transform events chain it;
--- predicate and session-op events interpret it.
---@alias kage.Event
---| "before_agent_start"
---| "agent_start"
---| "agent_end"
---| "turn_start"
---| "turn_end"
---| "message_start"
---| "message_update"
---| "message_end"
---| "after_provider_response"
---| "tool_call"
---| "tool_update"
---| "tool_result"
---| "session_open"
---| "session_close"
---| "model_select"
---| "thinking_level_select"
---| "user_bash"
---| "transform_context"
---| "before_provider_request"
---| "compact_prepare"
---| "should_stop_after_turn"
---| "session_before_switch"
---| "session_before_fork"
---| "session_before_tree"
---| "resources_discover"

--- One result a tool may return instead of a bare string.
---@class kage.ToolResult
---@field text string Output text shown to the agent.
---@field is_error? boolean Mark the call as failed.
---@field structured? table Machine-readable detail.

--- Spec passed to `kage.register_tool` / `kage.override_tool`.
---@class kage.ToolSpec
---@field name string Tool name the agent calls.
---@field description string One-line description for the model.
---@field schema table JSON schema for the input object.
---@field risk? kage.ToolRisk Permission tier; defaults to read.
---@field execute fun(input: table): string|kage.ToolResult|boolean|number|nil Tool body.

--- One declared command argument.
---@class kage.CommandArg
---@field name string Becomes `args.<name>`.
---@field kind kage.ArgKind Required.
---@field optional? boolean Defaults to false.
---@field choices? string[] Required when kind == choice.
---@field hint? string Placeholder for kind == text; defaults to value.

--- Spec passed to `kage.register_command`. The handler runs
--- through the coroutine bridge, so it may call the blocking
--- `kage.ui.*` dialogs directly.
---@class kage.CommandSpec
---@field name string No leading / or :.
---@field aliases? string[] Alternate names that resolve to this command.
---@field description string Shown in the palette and :help.
---@field args? kage.CommandArg[]
---@field handler fun(raw: string, ctx: table, args: table): string|kage.CommandResult|nil raw text, host ctx, parsed args by name.

--- Spec passed to `kage.register_widget`.
---@class kage.WidgetSpec
---@field key string Re-registering replaces in place.
---@field render fun(width: integer): string? Runs once per redraw.

--- One autocomplete candidate.
---@class kage.CompletionItem
---@field value string Replacement text (required).
---@field label? string Row label; defaults to value.
---@field detail? string Dim annotation.
---@field range? integer[] { from, to } 0-based byte span to replace.

--- Spec passed to `kage.add_autocomplete_provider`.
---@class kage.AutocompleteSpec
---@field name string Re-adding replaces in place.
---@field complete fun(prefix: string, ctx: { text: string, cursor: integer }): kage.CompletionItem[]

--- Key descriptor handed to a `kage.on_terminal_input` handler.
---@class kage.KeyEvent
---@field code string char|enter|esc|tab|backspace|up|down|left|right|home|end|pageup|pagedown|delete|insert|f1..f12|other.
---@field char? string Present only when code == char.
---@field ctrl boolean
---@field alt boolean
---@field shift boolean

--- Options for `kage.send_message`.
---@class kage.SendOpts
---@field trigger_turn? boolean Default true.
---@field deliver_as? "user" In v0.1 only user is wired.

--- Snapshot returned by `kage.context_usage`. The host fills
--- this in; the fields below are the conventional keys and
--- may vary by host version.
---@class kage.Usage
---@field model string
---@field input_tokens integer
---@field output_tokens integer
---@field context_window integer

--- Rich result a command handler may return instead of a string.
---@class kage.CommandResult
---@field text? string Output text shown to the user.
---@field is_error? boolean Mark the invocation as failed.
---@field structured? table Machine-readable detail.

--- Spec passed to `kage.acp.add_agent`.
---@class kage.AcpAgentSpec
---@field name string Agent id; required.
---@field command string Executable to spawn; required.
---@field args? string[] Command arguments.
---@field env? table String-to-string environment overrides.

--- Spec passed to `kage.mcp.add_server`.
---@class kage.McpServerSpec
---@field name string Server id; required.
---@field command string Executable to spawn; required.
---@field args? string[] Command arguments.
---@field env? table String-to-string environment overrides.
---@field disabled? boolean Declare but do not spawn; defaults to false.

--- Spec passed to `kage.register_provider`.
---@class kage.ProviderSpec
---@field id string Provider id; required.
---@field display_name? string Defaults to id.
---@field supports_caching? boolean Defaults to false.
---@field supports_thinking? boolean Defaults to false.
---@field supports_tool_use? boolean Defaults to true.
---@field stream fun(req: table): table[]|fun(): table? Yields provider event tables; required.

---@class kage
kage = {}

--- Wall-clock milliseconds since the Unix epoch.
---@return integer
function kage.now_ms() end

--- Record a structured log line at `level`.
---@param level kage.LogLevel
---@param message string
function kage.log(level, message) end

--- A copy of the host-supplied configuration table. Mutating
--- the returned table does not propagate back to the host.
---@return table
function kage.config() end

--- Back-compat alias for `kage.ui.notify`.
---@param message string
---@param level? kage.NotifyLevel
function kage.notify(message, level) end

--- Interactive UI surface.
---@class kage.ui
kage.ui = {}

--- Show a transient toast (stderr in print mode). Non-info
--- levels are also logged. Unknown level raises an error.
---@param message string
---@param level? kage.NotifyLevel
function kage.ui.notify(message, level) end

--- Open a fuzzy picker. Each item is a string or
--- `{ label, value?, detail? }`. Suspends the calling
--- coroutine; returns the chosen value, or nil if cancelled.
---@param title string
---@param items (string|{ label: string, value?: string, detail?: string })[]
---@return string|nil
function kage.ui.select(title, items) end

--- Open a yes/no overlay. Cancelling counts as false.
---@param title string
---@param message string
---@return boolean
function kage.ui.confirm(title, message) end

--- Open a single-line input. Returns the string, or nil if
--- cancelled. `placeholder` is dim help, not part of result.
---@param title string
---@param placeholder? string
---@return string|nil
function kage.ui.input(title, placeholder) end

--- Open a multi-line editor seeded with `prefill`. Ctrl+S
--- submits, Esc cancels. Returns the buffer, or nil.
---@param title string
---@param prefill? string
---@return string|nil
function kage.ui.editor(title, prefill) end

--- Take over the top status row. `fn(width)` runs each redraw
--- and returns a string, a span table, or an array of those.
--- Pass nil to restore the built-in status bar.
---@param fn fun(width: integer): any|nil
function kage.ui.set_header(fn) end

--- Take over the bottom modeline row. Same shape as set_header.
---@param fn fun(width: integer): any|nil
function kage.ui.set_footer(fn) end

--- Register a tool the agent can call like a built-in.
---@param spec kage.ToolSpec
function kage.register_tool(spec) end

--- Like `register_tool` but replaces the existing tool by
--- name. The host logs a warning if no such tool existed.
---@param spec kage.ToolSpec
function kage.override_tool(spec) end

--- Register a slash / colon command.
---@param spec kage.CommandSpec
function kage.register_command(spec) end

--- Like `register_command`, but allowed to shadow a built-in
--- command of the same name and dispatched ahead of it.
---@param spec kage.CommandSpec
function kage.override_command(spec) end

--- Own how a block of `kind` is drawn. `render` gets a block
--- table (`{ kind, width, ... }`) and returns the same shape
--- as `kage.ui.set_header`. A custom kind re-skins that block
--- type; the reserved names `user`/`assistant`/`thinking`/
--- `tool_call`/`tool_result`/`custom` override a built-in.
--- Pass `nil` to remove a renderer.
---@param kind string Custom block kind to take over.
---@param render fun(block: table): any|nil Gets { kind, text, width }; nil unregisters.
function kage.register_block_renderer(kind, render) end

--- Bind a chord to a handler. `spec` is a chord string or
--- `{ key, description? }`. The handler runs through the
--- coroutine bridge, so it may open `kage.ui.*` dialogs.
---@param spec string|{ key: string, description?: string }
---@param handler fun(): string?
function kage.register_keybinding(spec, handler) end

--- Add a prompt-input autocomplete provider. Providers form a
--- stack; the most recently added wins. Runs synchronously in
--- the shared Lua mutex, so keep it cheap.
---@param spec kage.AutocompleteSpec
function kage.add_autocomplete_provider(spec) end

--- Observe every key before any modal layer. A truthy return
--- consumes the event. Returns an `off` function that
--- unregisters this handler (idempotent). Prefer
--- register_keybinding unless you must swallow arbitrary keys.
---@param handler fun(ev: kage.KeyEvent): boolean
---@return fun()
function kage.on_terminal_input(handler) end

--- Register a status-bar widget.
---@param spec kage.WidgetSpec
function kage.register_widget(spec) end

--- Push or clear a transient status entry. Nil/empty clears.
---@param key string
---@param text string|nil
function kage.set_status(key, text) end

--- Clear a transient status entry.
---@param key string
function kage.clear_status(key) end

--- Subscribe to an event. Handlers fire in registration
--- order; a raising handler is logged and skipped.
--- Notification events ignore the return; transform events
--- chain it; predicate / session-op events interpret it.
---@param event kage.Event
---@param handler fun(payload: any): any
function kage.on(event, handler) end

--- Register a new LLM provider implementation. Advanced; see
--- the example plugins for a realistic shape.
---@param spec kage.ProviderSpec
function kage.register_provider(spec) end

--- Session inspection and control.
---@class kage.session
kage.session = {}

--- Sessions the host knows about: `{ id, value }` each.
---@return { id: string, value: string }[]
function kage.session.list() end

--- Fork the current session at entry-id prefix `at` (or the
--- latest entry when omitted). Performed between turns.
---@param at? string
function kage.session.fork(at) end

--- Append a custom entry to the session JSONL. `kind` is a
--- namespaced string; `data` is any table (defaults to {}).
---@param kind string
---@param data? table
function kage.session.append_entry(kind, data) end

--- Write a label pointing at entry id `anchor`. Nil clears.
---@param anchor string
---@param label? string
function kage.session.set_label(anchor, label) end

--- Queue a synthetic message delivered between turns.
---@param text string
---@param opts? kage.SendOpts
function kage.send_message(text, opts) end

--- Snapshot per-turn token usage. Nil until the host has run
--- at least one turn.
---@return kage.Usage|nil
function kage.context_usage() end

--- Ask the host to run a compaction pass. `prompt` is
--- advisory; the compact_prepare event is the precise hook.
---@param prompt? string
function kage.compact(prompt) end

--- Workdir-scoped filesystem access.
---@class kage.fs
kage.fs = {}

--- Read a file relative to the session workdir. Paths outside
--- the workdir tree raise an error.
---@param path string
---@return string
function kage.fs.read(path) end

--- Write a file under the workdir. Same restriction as read.
---@param path string
---@param content string
function kage.fs.write(path, content) end

--- Host-gated HTTP.
---@class kage.http
kage.http = {}

--- HTTP GET. The allow-list is host-controlled; unauthorized
--- hosts raise an error.
---@param url string
---@return { status: integer, body: string, content_type: string, truncated: boolean }
function kage.http.get(url) end

--- Declarative ACP agent config.
---@class kage.acp
kage.acp = {}

--- Declare an upstream ACP agent at runtime, mirroring
--- `[acp.agents.<name>]` in config.toml. Core spawns it.
---@param spec kage.AcpAgentSpec
function kage.acp.add_agent(spec) end

--- Register the single policy callback consulted when an
--- upstream ACP agent asks to run a tool. It must return a
--- boolean and must not open a dialog (no coroutine suspend):
--- it is policy, not UI. No handler, or a non-boolean or
--- erroring handler, denies.
---@param handler fun(req: table): boolean
function kage.on_acp_permission(handler) end

--- Declarative MCP server config.
---@class kage.mcp
kage.mcp = {}

--- Declare an MCP server at runtime, mirroring
--- `[mcp.servers.<name>]` in config.toml. Core spawns it.
---@param spec kage.McpServerSpec
function kage.mcp.add_server(spec) end

--- Names of the plugin-declared MCP servers, sorted.
---@return string[]
function kage.mcp.list_servers() end

--- Ask the host to restart a declared MCP server. Applied
--- between turns against the live manager.
---@param name string
function kage.mcp.restart(name) end

--- Theme inspection and switching.
---@class kage.theme
kage.theme = {}

--- The active theme name, or "" if none is set yet.
---@return string
function kage.theme.current() end

--- Theme names that may be passed to `kage.theme.set`.
---@return string[]
function kage.theme.list() end

--- Request a theme switch. The host validates and applies it
--- between turns. Errors on a non-string or empty name.
---@param name string
function kage.theme.set(name) end
