//! `gen-lua-types`: render `plugins/types/kage.lua` from one in-tree
//! spec.
//!
//! The spec below is the single source of truth for the
//! `lua-language-server` definition stub. `cargo xtask gen-lua-types`
//! writes the rendered file; `--check` re-renders and diffs without
//! writing (the CI drift gate). Editing the plugin API means editing
//! this spec and rerunning, so the shipped `.lua` never drifts from a
//! hand-maintained copy.
//!
//! This is the roadmap's "small in-tree DSL that already describes
//! each binding"; it intentionally replaces the sketched
//! `#[lua_export]` attribute approach, which (carrying only name/doc)
//! could not reproduce the `---@param` / `---@return` / `---@class`
//! detail the stub needs.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

/// One `---@param` / record `---@field`.
struct Field {
    /// Field name; suffix `?` for optional (rendered as emmylua
    /// optional and stripped from the displayed name).
    name: &'static str,
    ty: &'static str,
    doc: &'static str,
}

/// A `---@class` record type.
struct Class {
    name: &'static str,
    doc: &'static [&'static str],
    fields: &'static [Field],
}

/// A `---@alias` sum type. When any variant exceeds the inline budget
/// the renderer uses the multi-line `---| "x"` form.
struct Alias {
    name: &'static str,
    doc: &'static [&'static str],
    variants: &'static [&'static str],
}

/// A single function binding.
struct Func {
    doc: &'static [&'static str],
    /// Dotted path, e.g. `kage.ui.select`.
    path: &'static str,
    params: &'static [Field],
    ret: Option<&'static str>,
}

/// A sub-table to declare (`kage.ui = {}`) before its functions.
struct Table {
    /// Dotted path, e.g. `kage.ui`. `None` for top-level `kage`.
    path: &'static str,
    class_doc: &'static str,
}

const HEADER: &str = "\
---@meta
---
--- Type definitions for the `kage` plugin API.
---
--- GENERATED by `cargo xtask gen-lua-types` from xtask/src/luatypes.rs.
--- Do not edit by hand: edit the spec and regenerate. CI fails if this
--- file drifts from the spec.
---
--- This file is a `lua-language-server` definition stub: it declares
--- the shape of the `kage` global so editors give hover docs,
--- completion, and argument checking inside `*.lua` plugins. It ships
--- with the kage repo and is copied to
--- `~/.local/share/kage/types/kage.lua` by `kage init`, which also
--- writes a `.luarc.json` pointing the language server at it.
---
--- Nothing here runs: `---@meta` marks the whole file definitions-only.
--- The single source of truth for behavior is the Rust implementation
--- in `crates/kage-plugin`.";

const ALIASES: &[Alias] = &[
    Alias {
        name: "kage.LogLevel",
        doc: &["Levels accepted by `kage.log`."],
        variants: &["trace", "debug", "info", "warn", "error"],
    },
    Alias {
        name: "kage.NotifyLevel",
        doc: &["Levels accepted by `kage.ui.notify` / `kage.notify`."],
        variants: &["info", "warning", "error"],
    },
    Alias {
        name: "kage.ToolRisk",
        doc: &["Permission tier for a registered tool."],
        variants: &["read", "write", "network"],
    },
    Alias {
        name: "kage.ArgKind",
        doc: &["A declared command argument kind."],
        variants: &["text", "choice", "path", "session", "flag"],
    },
    Alias {
        name: "kage.Event",
        doc: &[
            "Every event name `kage.on` accepts. Notification events",
            "ignore the handler return; transform events chain it;",
            "predicate and session-op events interpret it.",
        ],
        variants: &[
            "before_agent_start",
            "agent_start",
            "agent_end",
            "turn_start",
            "turn_end",
            "message_start",
            "message_update",
            "message_end",
            "after_provider_response",
            "tool_call",
            "tool_update",
            "tool_result",
            "session_open",
            "session_close",
            "model_select",
            "thinking_level_select",
            "user_bash",
            "transform_context",
            "before_provider_request",
            "compact_prepare",
            "should_stop_after_turn",
            "session_before_switch",
            "session_before_fork",
            "session_before_tree",
            "resources_discover",
        ],
    },
];

const CLASSES: &[Class] = &[
    Class {
        name: "kage.ToolResult",
        doc: &["One result a tool may return instead of a bare string."],
        fields: &[
            Field {
                name: "text",
                ty: "string",
                doc: "Output text shown to the agent.",
            },
            Field {
                name: "is_error?",
                ty: "boolean",
                doc: "Mark the call as failed.",
            },
            Field {
                name: "structured?",
                ty: "table",
                doc: "Machine-readable detail.",
            },
        ],
    },
    Class {
        name: "kage.ToolSpec",
        doc: &["Spec passed to `kage.register_tool` / `kage.override_tool`."],
        fields: &[
            Field {
                name: "name",
                ty: "string",
                doc: "Tool name the agent calls.",
            },
            Field {
                name: "description",
                ty: "string",
                doc: "One-line description for the model.",
            },
            Field {
                name: "schema",
                ty: "table",
                doc: "JSON schema for the input object.",
            },
            Field {
                name: "risk?",
                ty: "kage.ToolRisk",
                doc: "Permission tier; defaults to read.",
            },
            Field {
                name: "execute",
                ty: "fun(input: table): string|kage.ToolResult",
                doc: "Tool body.",
            },
        ],
    },
    Class {
        name: "kage.CommandArg",
        doc: &["One declared command argument."],
        fields: &[
            Field {
                name: "name",
                ty: "string",
                doc: "Becomes `args.<name>`.",
            },
            Field {
                name: "kind?",
                ty: "kage.ArgKind",
                doc: "Defaults to text.",
            },
            Field {
                name: "choices?",
                ty: "string[]",
                doc: "Required when kind == choice.",
            },
        ],
    },
    Class {
        name: "kage.CommandSpec",
        doc: &[
            "Spec passed to `kage.register_command`. The handler runs",
            "through the coroutine bridge, so it may call the blocking",
            "`kage.ui.*` dialogs directly.",
        ],
        fields: &[
            Field {
                name: "name",
                ty: "string",
                doc: "No leading / or :.",
            },
            Field {
                name: "aliases?",
                ty: "string[]",
                doc: "Alternate names that resolve to this command.",
            },
            Field {
                name: "description",
                ty: "string",
                doc: "Shown in the palette and :help.",
            },
            Field {
                name: "args?",
                ty: "kage.CommandArg[]",
                doc: "",
            },
            Field {
                name: "handler",
                ty: "fun(args: table): string?",
                doc: "",
            },
        ],
    },
    Class {
        name: "kage.WidgetSpec",
        doc: &["Spec passed to `kage.register_widget`."],
        fields: &[
            Field {
                name: "key",
                ty: "string",
                doc: "Re-registering replaces in place.",
            },
            Field {
                name: "render",
                ty: "fun(width: integer): string?",
                doc: "Runs once per redraw.",
            },
        ],
    },
    Class {
        name: "kage.CompletionItem",
        doc: &["One autocomplete candidate."],
        fields: &[
            Field {
                name: "value",
                ty: "string",
                doc: "Replacement text (required).",
            },
            Field {
                name: "label?",
                ty: "string",
                doc: "Row label; defaults to value.",
            },
            Field {
                name: "detail?",
                ty: "string",
                doc: "Dim annotation.",
            },
            Field {
                name: "range?",
                ty: "integer[]",
                doc: "{ from, to } 0-based byte span to replace.",
            },
        ],
    },
    Class {
        name: "kage.AutocompleteSpec",
        doc: &["Spec passed to `kage.add_autocomplete_provider`."],
        fields: &[
            Field {
                name: "name",
                ty: "string",
                doc: "Re-adding replaces in place.",
            },
            Field {
                name: "complete",
                ty: "fun(prefix: string, ctx: { text: string, cursor: integer }): kage.CompletionItem[]",
                doc: "",
            },
        ],
    },
    Class {
        name: "kage.KeyEvent",
        doc: &["Key descriptor handed to a `kage.on_terminal_input` handler."],
        fields: &[
            Field {
                name: "code",
                ty: "string",
                doc: "char|enter|esc|tab|backtab|backspace|arrow/nav|f1..f12|other.",
            },
            Field {
                name: "char?",
                ty: "string",
                doc: "Present only when code == char.",
            },
            Field {
                name: "ctrl",
                ty: "boolean",
                doc: "",
            },
            Field {
                name: "alt",
                ty: "boolean",
                doc: "",
            },
            Field {
                name: "shift",
                ty: "boolean",
                doc: "",
            },
        ],
    },
    Class {
        name: "kage.SendOpts",
        doc: &["Options for `kage.send_message`."],
        fields: &[
            Field {
                name: "trigger_turn?",
                ty: "boolean",
                doc: "Default true.",
            },
            Field {
                name: "deliver_as?",
                ty: "\"user\"",
                doc: "In v0.1 only user is wired.",
            },
        ],
    },
    Class {
        name: "kage.Usage",
        doc: &["Per-turn token usage from `kage.context_usage`."],
        fields: &[
            Field {
                name: "model",
                ty: "string",
                doc: "",
            },
            Field {
                name: "input_tokens",
                ty: "integer",
                doc: "",
            },
            Field {
                name: "output_tokens",
                ty: "integer",
                doc: "",
            },
            Field {
                name: "context_window",
                ty: "integer",
                doc: "",
            },
        ],
    },
];

const TABLES: &[Table] = &[
    Table {
        path: "kage.ui",
        class_doc: "Interactive UI surface.",
    },
    Table {
        path: "kage.session",
        class_doc: "Session inspection and control.",
    },
    Table {
        path: "kage.fs",
        class_doc: "Workdir-scoped filesystem access.",
    },
    Table {
        path: "kage.http",
        class_doc: "Host-gated HTTP.",
    },
];

const FUNCS: &[Func] = &[
    Func {
        doc: &["Wall-clock milliseconds since the Unix epoch."],
        path: "kage.now_ms",
        params: &[],
        ret: Some("integer"),
    },
    Func {
        doc: &["Record a structured log line at `level`."],
        path: "kage.log",
        params: &[
            Field {
                name: "level",
                ty: "kage.LogLevel",
                doc: "",
            },
            Field {
                name: "message",
                ty: "string",
                doc: "",
            },
        ],
        ret: None,
    },
    Func {
        doc: &[
            "A copy of the host-supplied configuration table. Mutating",
            "the returned table does not propagate back to the host.",
        ],
        path: "kage.config",
        params: &[],
        ret: Some("table"),
    },
    Func {
        doc: &["Back-compat alias for `kage.ui.notify`."],
        path: "kage.notify",
        params: &[
            Field {
                name: "message",
                ty: "string",
                doc: "",
            },
            Field {
                name: "level?",
                ty: "kage.NotifyLevel",
                doc: "",
            },
        ],
        ret: None,
    },
    Func {
        doc: &[
            "Show a transient toast (stderr in print mode). Non-info",
            "levels are also logged. Unknown level raises an error.",
        ],
        path: "kage.ui.notify",
        params: &[
            Field {
                name: "message",
                ty: "string",
                doc: "",
            },
            Field {
                name: "level?",
                ty: "kage.NotifyLevel",
                doc: "",
            },
        ],
        ret: None,
    },
    Func {
        doc: &[
            "Open a fuzzy picker. Each item is a string or",
            "`{ label, value?, detail? }`. Suspends the calling",
            "coroutine; returns the chosen value, or nil if cancelled.",
        ],
        path: "kage.ui.select",
        params: &[
            Field {
                name: "title",
                ty: "string",
                doc: "",
            },
            Field {
                name: "items",
                ty: "(string|{ label: string, value?: string, detail?: string })[]",
                doc: "",
            },
        ],
        ret: Some("string|nil"),
    },
    Func {
        doc: &["Open a yes/no overlay. Cancelling counts as false."],
        path: "kage.ui.confirm",
        params: &[
            Field {
                name: "title",
                ty: "string",
                doc: "",
            },
            Field {
                name: "message",
                ty: "string",
                doc: "",
            },
        ],
        ret: Some("boolean"),
    },
    Func {
        doc: &[
            "Open a single-line input. Returns the string, or nil if",
            "cancelled. `placeholder` is dim help, not part of result.",
        ],
        path: "kage.ui.input",
        params: &[
            Field {
                name: "title",
                ty: "string",
                doc: "",
            },
            Field {
                name: "placeholder?",
                ty: "string",
                doc: "",
            },
        ],
        ret: Some("string|nil"),
    },
    Func {
        doc: &[
            "Open a multi-line editor seeded with `prefill`. Ctrl+S",
            "submits, Esc cancels. Returns the buffer, or nil.",
        ],
        path: "kage.ui.editor",
        params: &[
            Field {
                name: "title",
                ty: "string",
                doc: "",
            },
            Field {
                name: "prefill?",
                ty: "string",
                doc: "",
            },
        ],
        ret: Some("string|nil"),
    },
    Func {
        doc: &[
            "Take over the top status row. `fn(width)` runs each redraw",
            "and returns a string, a span table, or an array of those.",
            "Pass nil to restore the built-in status bar.",
        ],
        path: "kage.ui.set_header",
        params: &[Field {
            name: "fn",
            ty: "fun(width: integer): any|nil",
            doc: "",
        }],
        ret: None,
    },
    Func {
        doc: &["Take over the bottom modeline row. Same shape as set_header."],
        path: "kage.ui.set_footer",
        params: &[Field {
            name: "fn",
            ty: "fun(width: integer): any|nil",
            doc: "",
        }],
        ret: None,
    },
    Func {
        doc: &["Register a tool the agent can call like a built-in."],
        path: "kage.register_tool",
        params: &[Field {
            name: "spec",
            ty: "kage.ToolSpec",
            doc: "",
        }],
        ret: None,
    },
    Func {
        doc: &[
            "Like `register_tool` but replaces the existing tool by",
            "name. The host logs a warning if no such tool existed.",
        ],
        path: "kage.override_tool",
        params: &[Field {
            name: "spec",
            ty: "kage.ToolSpec",
            doc: "",
        }],
        ret: None,
    },
    Func {
        doc: &["Register a slash / colon command."],
        path: "kage.register_command",
        params: &[Field {
            name: "spec",
            ty: "kage.CommandSpec",
            doc: "",
        }],
        ret: None,
    },
    Func {
        doc: &[
            "Like `register_command`, but allowed to shadow a built-in",
            "command of the same name and dispatched ahead of it.",
        ],
        path: "kage.override_command",
        params: &[Field {
            name: "spec",
            ty: "kage.CommandSpec",
            doc: "",
        }],
        ret: None,
    },
    Func {
        doc: &[
            "Own how a block of `kind` is drawn. `render` gets a block",
            "table (`{ kind, width, ... }`) and returns the same shape",
            "as `kage.ui.set_header`. A custom kind re-skins that block",
            "type; the reserved names `user`/`assistant`/`thinking`/",
            "`tool_call`/`tool_result`/`custom` override a built-in.",
            "Pass `nil` to remove a renderer.",
        ],
        path: "kage.register_block_renderer",
        params: &[
            Field {
                name: "kind",
                ty: "string",
                doc: "Custom block kind to take over.",
            },
            Field {
                name: "render",
                ty: "fun(block: table): any|nil",
                doc: "Gets { kind, text, width }; nil unregisters.",
            },
        ],
        ret: None,
    },
    Func {
        doc: &[
            "Bind a chord to a handler. `spec` is a chord string or",
            "`{ key, description? }`. The handler runs through the",
            "coroutine bridge, so it may open `kage.ui.*` dialogs.",
        ],
        path: "kage.register_keybinding",
        params: &[
            Field {
                name: "spec",
                ty: "string|{ key: string, description?: string }",
                doc: "",
            },
            Field {
                name: "handler",
                ty: "fun(): string?",
                doc: "",
            },
        ],
        ret: None,
    },
    Func {
        doc: &[
            "Add a prompt-input autocomplete provider. Providers form a",
            "stack; the most recently added wins. Runs synchronously in",
            "the shared Lua mutex, so keep it cheap.",
        ],
        path: "kage.add_autocomplete_provider",
        params: &[Field {
            name: "spec",
            ty: "kage.AutocompleteSpec",
            doc: "",
        }],
        ret: None,
    },
    Func {
        doc: &[
            "Observe every key before any modal layer. A truthy return",
            "consumes the event. Returns an `off` function that",
            "unregisters this handler (idempotent). Prefer",
            "register_keybinding unless you must swallow arbitrary keys.",
        ],
        path: "kage.on_terminal_input",
        params: &[Field {
            name: "handler",
            ty: "fun(ev: kage.KeyEvent): boolean",
            doc: "",
        }],
        ret: Some("fun()"),
    },
    Func {
        doc: &["Register a status-bar widget."],
        path: "kage.register_widget",
        params: &[Field {
            name: "spec",
            ty: "kage.WidgetSpec",
            doc: "",
        }],
        ret: None,
    },
    Func {
        doc: &["Push or clear a transient status entry. Nil/empty clears."],
        path: "kage.set_status",
        params: &[
            Field {
                name: "key",
                ty: "string",
                doc: "",
            },
            Field {
                name: "text",
                ty: "string|nil",
                doc: "",
            },
        ],
        ret: None,
    },
    Func {
        doc: &["Clear a transient status entry."],
        path: "kage.clear_status",
        params: &[Field {
            name: "key",
            ty: "string",
            doc: "",
        }],
        ret: None,
    },
    Func {
        doc: &[
            "Subscribe to an event. Handlers fire in registration",
            "order; a raising handler is logged and skipped.",
            "Notification events ignore the return; transform events",
            "chain it; predicate / session-op events interpret it.",
        ],
        path: "kage.on",
        params: &[
            Field {
                name: "event",
                ty: "kage.Event",
                doc: "",
            },
            Field {
                name: "handler",
                ty: "fun(payload: any): any",
                doc: "",
            },
        ],
        ret: None,
    },
    Func {
        doc: &[
            "Register a new LLM provider implementation. Advanced; see",
            "the example plugins for a realistic shape.",
        ],
        path: "kage.register_provider",
        params: &[Field {
            name: "spec",
            ty: "table",
            doc: "",
        }],
        ret: None,
    },
    Func {
        doc: &["Sessions the host knows about: `{ id, value }` each."],
        path: "kage.session.list",
        params: &[],
        ret: Some("{ id: string, value: string }[]"),
    },
    Func {
        doc: &[
            "Fork the current session at entry-id prefix `at` (or the",
            "latest entry when omitted). Performed between turns.",
        ],
        path: "kage.session.fork",
        params: &[Field {
            name: "at?",
            ty: "string",
            doc: "",
        }],
        ret: None,
    },
    Func {
        doc: &[
            "Append a custom entry to the session JSONL. `kind` is a",
            "namespaced string; `data` is any table (defaults to {}).",
        ],
        path: "kage.session.append_entry",
        params: &[
            Field {
                name: "kind",
                ty: "string",
                doc: "",
            },
            Field {
                name: "data?",
                ty: "table",
                doc: "",
            },
        ],
        ret: None,
    },
    Func {
        doc: &["Write a label pointing at entry id `anchor`. Nil clears."],
        path: "kage.session.set_label",
        params: &[
            Field {
                name: "anchor",
                ty: "string",
                doc: "",
            },
            Field {
                name: "label?",
                ty: "string",
                doc: "",
            },
        ],
        ret: None,
    },
    Func {
        doc: &["Queue a synthetic message delivered between turns."],
        path: "kage.send_message",
        params: &[
            Field {
                name: "text",
                ty: "string",
                doc: "",
            },
            Field {
                name: "opts?",
                ty: "kage.SendOpts",
                doc: "",
            },
        ],
        ret: None,
    },
    Func {
        doc: &[
            "Snapshot per-turn token usage. Nil until the host has run",
            "at least one turn.",
        ],
        path: "kage.context_usage",
        params: &[],
        ret: Some("kage.Usage|nil"),
    },
    Func {
        doc: &[
            "Ask the host to run a compaction pass. `prompt` is",
            "advisory; the compact_prepare event is the precise hook.",
        ],
        path: "kage.compact",
        params: &[Field {
            name: "prompt?",
            ty: "string",
            doc: "",
        }],
        ret: None,
    },
    Func {
        doc: &[
            "Read a file relative to the session workdir. Paths outside",
            "the workdir tree raise an error.",
        ],
        path: "kage.fs.read",
        params: &[Field {
            name: "path",
            ty: "string",
            doc: "",
        }],
        ret: Some("string"),
    },
    Func {
        doc: &["Write a file under the workdir. Same restriction as read."],
        path: "kage.fs.write",
        params: &[
            Field {
                name: "path",
                ty: "string",
                doc: "",
            },
            Field {
                name: "contents",
                ty: "string",
                doc: "",
            },
        ],
        ret: None,
    },
    Func {
        doc: &[
            "HTTP GET. The allow-list is host-controlled; unauthorized",
            "hosts raise an error.",
        ],
        path: "kage.http.get",
        params: &[Field {
            name: "url",
            ty: "string",
            doc: "",
        }],
        ret: Some("{ status: integer, body: string, headers: table }"),
    },
];

/// Repo path of the generated stub, relative to the workspace root.
fn stub_path() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .map(Path::to_path_buf)
        .unwrap_or_default()
        .join("plugins")
        .join("types")
        .join("kage.lua")
}

fn doc_lines(out: &mut String, doc: &[&str]) {
    for line in doc {
        if line.is_empty() {
            out.push_str("---\n");
        } else {
            let _ = writeln!(out, "--- {line}");
        }
    }
}

/// Strip a trailing `?` (optional marker) from a field name.
fn bare(name: &str) -> &str {
    name.strip_suffix('?').unwrap_or(name)
}

/// Render the whole stub deterministically from the spec.
#[must_use]
pub fn render() -> String {
    let mut s = String::new();
    s.push_str(HEADER);
    s.push('\n');

    for a in ALIASES {
        s.push('\n');
        doc_lines(&mut s, a.doc);
        if a.variants.len() <= 5 {
            let joined = a
                .variants
                .iter()
                .map(|v| format!("\"{v}\""))
                .collect::<Vec<_>>()
                .join("|");
            let _ = writeln!(s, "---@alias {} {joined}", a.name);
        } else {
            let _ = writeln!(s, "---@alias {}", a.name);
            for v in a.variants {
                let _ = writeln!(s, "---| \"{v}\"");
            }
        }
    }

    for c in CLASSES {
        s.push('\n');
        doc_lines(&mut s, c.doc);
        let _ = writeln!(s, "---@class {}", c.name);
        for f in c.fields {
            let opt = if f.name.ends_with('?') { "?" } else { "" };
            let tail = if f.doc.is_empty() {
                String::new()
            } else {
                format!(" {}", f.doc)
            };
            let _ = writeln!(s, "---@field {}{opt} {}{tail}", bare(f.name), f.ty);
        }
    }

    // Declare `kage` as a GLOBAL, not a `local` module. The host
    // injects `kage` as a global into every plugin; modelling it as a
    // local module (with a trailing `return kage`) makes
    // lua-language-server treat references in plugin files as
    // undefined globals. A global `---@class kage` table with no
    // return types the injected global correctly and keeps
    // `lua-language-server --check` clean on real plugins.
    s.push_str("\n---@class kage\nkage = {}\n");

    let mut declared: Vec<&str> = Vec::new();
    for f in FUNCS {
        // Declare any sub-table the function lives on, once, in spec
        // order, just before its first function.
        if let Some((table, _)) = f.path.rsplit_once('.')
            && table != "kage"
            && !declared.contains(&table)
        {
            if let Some(t) = TABLES.iter().find(|t| t.path == table) {
                s.push('\n');
                let _ = writeln!(s, "--- {}", t.class_doc);
                let _ = writeln!(s, "---@class {table}");
                let _ = writeln!(s, "{table} = {{}}");
            }
            declared.push(table);
        }
        s.push('\n');
        doc_lines(&mut s, f.doc);
        let mut args: Vec<String> = Vec::new();
        for p in f.params {
            let opt = if p.name.ends_with('?') { "?" } else { "" };
            let tail = if p.doc.is_empty() {
                String::new()
            } else {
                format!(" {}", p.doc)
            };
            let _ = writeln!(s, "---@param {}{opt} {}{tail}", bare(p.name), p.ty);
            args.push(bare(p.name).to_owned());
        }
        if let Some(ret) = f.ret {
            let _ = writeln!(s, "---@return {ret}");
        }
        let _ = writeln!(s, "function {}({}) end", f.path, args.join(", "));
    }

    // No trailing `return kage`: this is a global definition file, not
    // a module. (`---@meta` already marks it definitions-only.)
    s
}

/// `cargo xtask gen-lua-types [--check]`. Writes the stub, or in
/// check mode returns an error when the committed file is stale.
pub fn run(check: bool) -> Result<PathBuf, String> {
    let path = stub_path();
    let rendered = render();
    if check {
        let on_disk =
            std::fs::read_to_string(&path).map_err(|e| format!("read {}: {e}", path.display()))?;
        if on_disk != rendered {
            return Err(format!(
                "{} is out of date; run `cargo xtask gen-lua-types`",
                path.display()
            ));
        }
        return Ok(path);
    }
    std::fs::write(&path, &rendered).map_err(|e| format!("write {}: {e}", path.display()))?;
    Ok(path)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn render_is_deterministic() {
        assert_eq!(render(), render());
    }

    #[test]
    fn render_declares_kage_as_a_global() {
        let s = render();
        assert!(s.starts_with("---@meta\n"));
        assert!(s.contains("---@class kage\nkage = {}\n"));
        // It is a global definition file: no `local` shadow, no
        // module `return` statement (which would make plugin-file
        // references read as undefined globals to
        // lua-language-server). Checked as a statement, not a
        // substring, so `---@return kage.Usage` does not trip it.
        assert!(!s.contains("local kage = {}"));
        assert!(!s.contains("\nreturn kage"));
        assert!(!s.trim_end().ends_with("return kage"));
    }

    #[test]
    fn every_func_path_is_emitted() {
        let s = render();
        for f in FUNCS {
            assert!(
                s.contains(&format!("function {}(", f.path)),
                "missing {}",
                f.path
            );
        }
    }

    #[test]
    fn sub_tables_are_declared_once_before_use() {
        let s = render();
        for t in TABLES {
            let decl = format!("{} = {{}}", t.path);
            assert_eq!(
                s.matches(&decl).count(),
                1,
                "{} should be declared exactly once",
                t.path
            );
        }
    }

    #[test]
    fn long_unions_use_multiline_form() {
        let s = render();
        // kage.Event has > 5 variants -> multi-line `---| "x"`.
        assert!(s.contains("---@alias kage.Event\n---| \"before_agent_start\""));
        // Short alias stays inline.
        assert!(s.contains(r#"---@alias kage.LogLevel "trace"|"debug""#));
    }
}
