//! `gen-lua-types`: render `plugins/types/kage.lua` from the
//! single-source spec that lives in `kage-plugin`.
//!
//! The spec is [`kage_plugin::spec::surface`] - the same description
//! the crate uses to reason about its own Lua surface, and which a
//! `kage-plugin` test pins to the actually-installed bindings. This
//! command only renders that spec into the `lua-language-server`
//! definition stub; `--check` re-renders and diffs without writing
//! (the CI drift gate). Editing the plugin API means editing the spec
//! in `crates/kage-plugin/src/spec.rs` and rerunning, so the shipped
//! `.lua` cannot drift from the Rust bindings.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use kage_plugin::spec;

const HEADER: &str = "\
---@meta
---
--- Type definitions for the `kage` plugin API.
---
--- GENERATED by `cargo xtask gen-lua-types` from the kage-plugin spec
--- (`crates/kage-plugin/src/spec.rs`). Do not edit by hand: edit that
--- spec and regenerate. CI fails if this file drifts from it.
---
--- This file is a `lua-language-server` definition stub: it declares
--- the shape of the `kage` global so editors give hover docs,
--- completion, and argument checking inside `*.lua` plugins. It ships
--- with the kage repo and is copied to
--- `~/.local/share/kage/types/kage.lua` by `kage init`, which also
--- writes a `.luarc.json` pointing the language server at it.
---
--- Nothing here runs: `---@meta` marks the whole file definitions-only.
--- The single source of truth for behavior is the Rust implementation
--- in `crates/kage-plugin`.";

/// Repo path of the generated stub, relative to the workspace root.
fn stub_path() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .map(Path::to_path_buf)
        .unwrap_or_default()
        .join("plugins")
        .join("types")
        .join("kage.lua")
}

fn doc_lines(out: &mut String, doc: &[&str]) {
    for line in doc {
        if line.is_empty() {
            out.push_str("---\n");
        } else {
            let _ = writeln!(out, "--- {line}");
        }
    }
}

/// Strip a trailing `?` (optional marker) from a field name.
fn bare(name: &str) -> &str {
    name.strip_suffix('?').unwrap_or(name)
}

/// Render the whole stub deterministically from the spec.
#[must_use]
pub fn render() -> String {
    let surface = spec::surface();
    let mut s = String::new();
    s.push_str(HEADER);
    s.push('\n');

    for a in surface.aliases {
        s.push('\n');
        doc_lines(&mut s, a.doc);
        if a.variants.len() <= 5 {
            let joined = a
                .variants
                .iter()
                .map(|v| format!("\"{v}\""))
                .collect::<Vec<_>>()
                .join("|");
            let _ = writeln!(s, "---@alias {} {joined}", a.name);
        } else {
            let _ = writeln!(s, "---@alias {}", a.name);
            for v in a.variants {
                let _ = writeln!(s, "---| \"{v}\"");
            }
        }
    }

    for c in surface.classes {
        s.push('\n');
        doc_lines(&mut s, c.doc);
        let _ = writeln!(s, "---@class {}", c.name);
        for f in c.fields {
            let opt = if f.name.ends_with('?') { "?" } else { "" };
            let tail = if f.doc.is_empty() {
                String::new()
            } else {
                format!(" {}", f.doc)
            };
            let _ = writeln!(s, "---@field {}{opt} {}{tail}", bare(f.name), f.ty);
        }
    }

    // Declare `kage` as a GLOBAL, not a `local` module. The host
    // injects `kage` as a global into every plugin; modelling it as a
    // local module (with a trailing `return kage`) makes
    // lua-language-server treat references in plugin files as
    // undefined globals. A global `---@class kage` table with no
    // return types the injected global correctly and keeps
    // `lua-language-server --check` clean on real plugins.
    s.push_str("\n---@class kage\nkage = {}\n");

    // Base functions, then capability-gated ones. Gated functions are
    // rendered the same way (so editors still offer them when the
    // plugin has the capability); their doc already states the
    // requirement. They share the `declared` set so a sub-table is
    // still declared exactly once.
    let mut declared: Vec<&'static str> = Vec::new();
    for f in surface.funcs {
        emit_func(&mut s, &mut declared, surface.tables, f);
    }
    for g in surface.gated {
        emit_func(&mut s, &mut declared, surface.tables, &g.func);
    }

    // No trailing `return kage`: this is a global definition file, not
    // a module. (`---@meta` already marks it definitions-only.)
    s
}

/// Emit one function: its sub-table declaration (once), doc, params,
/// return, and stub body.
fn emit_func(
    s: &mut String,
    declared: &mut Vec<&'static str>,
    tables: &'static [spec::Table],
    f: &'static spec::Func,
) {
    // Declare any sub-table the function lives on, once, in spec
    // order, just before its first function.
    if let Some((table, _)) = f.path.rsplit_once('.')
        && table != "kage"
        && !declared.contains(&table)
    {
        if let Some(t) = tables.iter().find(|t| t.path == table) {
            s.push('\n');
            let _ = writeln!(s, "--- {}", t.class_doc);
            let _ = writeln!(s, "---@class {table}");
            let _ = writeln!(s, "{table} = {{}}");
        }
        declared.push(table);
    }
    s.push('\n');
    doc_lines(s, f.doc);
    let mut args: Vec<String> = Vec::new();
    for p in f.params {
        let opt = if p.name.ends_with('?') { "?" } else { "" };
        let tail = if p.doc.is_empty() {
            String::new()
        } else {
            format!(" {}", p.doc)
        };
        let _ = writeln!(s, "---@param {}{opt} {}{tail}", bare(p.name), p.ty);
        args.push(bare(p.name).to_owned());
    }
    if let Some(ret) = f.ret {
        let _ = writeln!(s, "---@return {ret}");
    }
    let _ = writeln!(s, "function {}({}) end", f.path, args.join(", "));
}

/// `cargo xtask gen-lua-types [--check]`. Writes the stub, or in
/// check mode returns an error when the committed file is stale.
pub fn run(check: bool) -> Result<PathBuf, String> {
    let path = stub_path();
    let rendered = render();
    if check {
        let on_disk =
            std::fs::read_to_string(&path).map_err(|e| format!("read {}: {e}", path.display()))?;
        if on_disk != rendered {
            return Err(format!(
                "{} is out of date; run `cargo xtask gen-lua-types`",
                path.display()
            ));
        }
        return Ok(path);
    }
    std::fs::write(&path, &rendered).map_err(|e| format!("write {}: {e}", path.display()))?;
    Ok(path)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn render_is_deterministic() {
        assert_eq!(render(), render());
    }

    #[test]
    fn render_declares_kage_as_a_global() {
        let s = render();
        assert!(s.starts_with("---@meta\n"));
        assert!(s.contains("---@class kage\nkage = {}\n"));
        // It is a global definition file: no `local` shadow, no
        // module `return` statement (which would make plugin-file
        // references read as undefined globals to
        // lua-language-server). Checked as a statement, not a
        // substring, so `---@return kage.Usage` does not trip it.
        assert!(!s.contains("local kage = {}"));
        assert!(!s.contains("\nreturn kage"));
        assert!(!s.trim_end().ends_with("return kage"));
    }

    #[test]
    fn every_func_path_is_emitted() {
        let s = render();
        let surface = spec::surface();
        let paths = surface
            .funcs
            .iter()
            .map(|f| f.path)
            .chain(surface.gated.iter().map(|g| g.func.path));
        for path in paths {
            assert!(s.contains(&format!("function {path}(")), "missing {path}");
        }
    }

    #[test]
    fn sub_tables_are_declared_once_before_use() {
        let s = render();
        for t in spec::surface().tables {
            let decl = format!("{} = {{}}", t.path);
            assert_eq!(
                s.matches(&decl).count(),
                1,
                "{} should be declared exactly once",
                t.path
            );
        }
    }

    #[test]
    fn long_unions_use_multiline_form() {
        let s = render();
        // kage.Event has > 5 variants -> multi-line `---| "x"`.
        assert!(s.contains("---@alias kage.Event\n---| \"before_agent_start\""));
        // Short alias stays inline.
        assert!(s.contains(r#"---@alias kage.LogLevel "trace"|"debug""#));
    }
}
