//! `cargo xtask` - workspace housekeeping commands.
//!
//! Layering: build tooling outside the runtime crate layering; depends
//! on `kage-plugin` and `kage-provider`.
//!
//! Subcommands:
//!
//! * `refresh-models`: fetch `https://models.dev/api.json`, curate the
//!   subset kage needs with `kage_provider::catalog::source`, and
//!   rewrite `crates/kage-provider/src/catalog/generated.rs`. This is
//!   run by maintainers; `cargo build` itself is offline.
//! * `gen-lua-types`: regenerate `plugins/types/kage.lua`.
//! * `check-ascii`: the ASCII-only source gate.

use std::fmt::Write as _;
use std::fs;
use std::io::Read as _;
use std::path::PathBuf;
use std::process::ExitCode;

use clap::{Parser, Subcommand};
use kage_core::{Inputs, Reasoning};
use kage_provider::catalog::source::{
    self, MODELS_DEV_URL, SUPPORTED_PROVIDERS, SourceModel, SourceProvider,
};

mod ascii;
mod luatypes;

#[derive(Parser, Debug)]
#[command(version, about, long_about = None)]
struct Cli {
    #[command(subcommand)]
    command: Command,
}

#[derive(Subcommand, Debug)]
enum Command {
    /// Re-fetch and regenerate the provider/model catalog.
    RefreshModels {
        /// Override the upstream URL (handy for offline / fixture testing).
        #[arg(long, default_value = MODELS_DEV_URL)]
        source: String,
    },
    /// Regenerate `plugins/types/kage.lua` from the in-tree spec.
    GenLuaTypes {
        /// Do not write; fail if the committed file is out of date
        /// (the CI drift gate).
        #[arg(long)]
        check: bool,
    },
    /// Fail if any Rust source carries raw non-ASCII bytes (the CI
    /// ASCII-only gate). Unicode glyphs must use `\u{..}` escapes.
    CheckAscii,
}

fn main() -> ExitCode {
    let cli = Cli::parse();
    match cli.command {
        Command::RefreshModels { source } => match refresh_models(&source) {
            Ok(path) => {
                eprintln!("xtask: wrote {}", path.display());
                ExitCode::SUCCESS
            }
            Err(e) => {
                eprintln!("xtask: refresh-models failed: {e}");
                ExitCode::from(1)
            }
        },
        Command::GenLuaTypes { check } => match luatypes::run(check) {
            Ok(path) => {
                let verb = if check { "up to date" } else { "wrote" };
                eprintln!("xtask: {verb} {}", path.display());
                ExitCode::SUCCESS
            }
            Err(e) => {
                eprintln!("xtask: gen-lua-types failed: {e}");
                ExitCode::from(1)
            }
        },
        Command::CheckAscii => match ascii::run() {
            Ok(()) => {
                eprintln!("xtask: source is ASCII-only");
                ExitCode::SUCCESS
            }
            Err(e) => {
                eprintln!("xtask: check-ascii failed: {e}");
                ExitCode::from(1)
            }
        },
    }
}

fn refresh_models(source_url: &str) -> Result<PathBuf, String> {
    let raw = fetch(source_url)?;
    let providers = source::parse(&raw)?;
    for map in SUPPORTED_PROVIDERS {
        if !providers.iter().any(|p| p.id == map.kage_id) {
            return Err(format!("upstream missing provider '{}'", map.api_id));
        }
    }
    let dest = workspace_root().join("crates/kage-provider/src/catalog/generated.rs");
    fs::write(&dest, render(&providers)).map_err(|e| format!("write {}: {e}", dest.display()))?;
    let status = std::process::Command::new("rustfmt")
        .args(["--edition", "2024"])
        .arg(&dest)
        .status()
        .map_err(|e| format!("run rustfmt: {e}"))?;
    if !status.success() {
        return Err(format!("rustfmt failed on {}", dest.display()));
    }
    Ok(dest)
}

fn fetch(url: &str) -> Result<String, String> {
    if let Some(path) = url.strip_prefix("file://") {
        return fs::read_to_string(path).map_err(|e| format!("read {path}: {e}"));
    }
    let agent = ureq::Agent::new_with_defaults();
    let response = agent
        .get(url)
        .header("user-agent", "kage-xtask/0.1")
        .call()
        .map_err(|e| format!("get {url}: {e}"))?;
    let mut body = String::new();
    response
        .into_body()
        .into_reader()
        .take(32 * 1024 * 1024)
        .read_to_string(&mut body)
        .map_err(|e| format!("read body: {e}"))?;
    Ok(body)
}

fn render(providers: &[SourceProvider]) -> String {
    let mut out = String::new();
    out.push_str(
        "//! @generated by `cargo xtask refresh-models`. Do not edit by hand.\n\
         //!\n\
         //! Source: <https://models.dev/api.json>, curated to kage's supported providers.\n\
         \n\
         #![allow(clippy::unreadable_literal)]\n\
         \n\
         #[allow(unused_imports)]\n\
         use super::{ModelCost, ModelInfo, ProviderInfo};\n\
         #[allow(unused_imports)]\n\
         use kage_core::{Effort, Efforts, Input, Inputs, Reasoning, ReasoningField};\n\
         \n",
    );
    let _ = writeln!(out, "/// Static provider/model catalog.");
    let _ = writeln!(out, "pub static PROVIDERS: &[ProviderInfo] = &[");
    for p in providers {
        emit_provider(&mut out, p);
    }
    out.push_str("];\n");
    out
}

fn emit_provider(out: &mut String, p: &SourceProvider) {
    let _ = writeln!(out, "    ProviderInfo {{");
    let _ = writeln!(out, "        id: {},", quote(&p.id));
    let _ = writeln!(out, "        name: {},", quote(&p.name));
    let _ = writeln!(out, "        api: {},", opt_quote(p.api.as_deref()));
    out.push_str("        models: &[\n");
    for m in &p.models {
        emit_model(out, m);
    }
    out.push_str("        ],\n");
    out.push_str("    },\n");
}

fn emit_model(out: &mut String, m: &SourceModel) {
    let _ = writeln!(out, "ModelInfo {{");
    let _ = writeln!(out, "id: {},", quote(&m.id));
    let _ = writeln!(out, "name: {},", quote(&m.name));
    let _ = writeln!(out, "context: {},", opt_int(m.context));
    let _ = writeln!(out, "input_limit: {},", opt_int(m.input_limit));
    let _ = writeln!(out, "output: {},", opt_int(m.output));
    let _ = writeln!(out, "reasoning: {},", reasoning_expr(m.reasoning));
    let _ = writeln!(out, "input: {},", inputs_expr(m.input));
    match m.interleaved {
        Some(field) => {
            let _ = writeln!(out, "interleaved: Some(ReasoningField::{field:?}),");
        }
        None => out.push_str("interleaved: None,\n"),
    }
    let _ = writeln!(
        out,
        "release_date: {},",
        opt_quote(m.release_date.as_deref())
    );
    match &m.cost {
        Some(c) => {
            let _ = writeln!(out, "cost: Some(ModelCost {{");
            let _ = writeln!(out, "input: {:.6},", c.input);
            let _ = writeln!(out, "output: {:.6},", c.output);
            let _ = writeln!(out, "cache_read: {},", opt_float(c.cache_read));
            let _ = writeln!(out, "cache_write: {},", opt_float(c.cache_write));
            out.push_str("}),\n");
        }
        None => out.push_str("cost: None,\n"),
    }
    out.push_str("},\n");
}

fn reasoning_expr(r: Reasoning) -> String {
    match r {
        Reasoning::Unknown => "Reasoning::Unknown".to_owned(),
        Reasoning::None => "Reasoning::None".to_owned(),
        Reasoning::Fixed => "Reasoning::Fixed".to_owned(),
        Reasoning::Toggle => "Reasoning::Toggle".to_owned(),
        Reasoning::Effort { efforts, toggle } => {
            let list: Vec<String> = efforts.iter().map(|e| format!("Effort::{e:?}")).collect();
            format!(
                "Reasoning::Effort {{ efforts: Efforts::of(&[{}]), toggle: {toggle} }}",
                list.join(", ")
            )
        }
        Reasoning::Budget { min, max, toggle } => format!(
            "Reasoning::Budget {{ min: {min}, max: {}, toggle: {toggle} }}",
            opt_int(max.map(u64::from))
        ),
    }
}

fn inputs_expr(inputs: Inputs) -> String {
    let list: Vec<String> = inputs.iter().map(|i| format!("Input::{i:?}")).collect();
    format!("Inputs::of(&[{}])", list.join(", "))
}

fn opt_float(v: Option<f64>) -> String {
    match v {
        Some(n) => format!("Some({n:.6})"),
        None => "None".to_owned(),
    }
}

fn quote(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => {
                let _ = write!(out, "\\u{{{:04x}}}", c as u32);
            }
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

fn opt_quote(s: Option<&str>) -> String {
    match s {
        Some(s) => format!("Some({})", quote(s)),
        None => "None".to_owned(),
    }
}

fn opt_int(v: Option<u64>) -> String {
    match v {
        Some(n) => format!("Some({n})"),
        None => "None".to_owned(),
    }
}

fn workspace_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .map(PathBuf::from)
        .expect("xtask is a workspace member; parent exists")
}
