[package]
name = "kage-tui"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
base64.workspace = true
kage-core.workspace = true
kage-loop.workspace = true
kage-plugin.workspace = true
ratatui.workspace = true
serde_json.workspace = true
syntect.workspace = true
thiserror.workspace = true
